### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by stanleySimeon** [vickymarz/awesome-books#2]
Review open

**Comment by stanleySimeon** [comment]
# You have made a good wiork work, but i think your have some optional issues:

 - Inside a function you can create a variable with var when it will not be reassigned.

Cheers and happy codding!👏🏾😁

**Comment by TEMESGEN-G25** [comment]
# Nicely done! Your project is clean and I can hardly see any issues. But there's one simple issue you missed: 

- Your live demo link isn't showing the page of your website.
